version: "3"

services:
  postgres:
    image: postgres
    container_name: migra.postgres
    environment:
      POSTGRES_DB: "migra_tests"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - 6000:5432

  mysql:
    image: mysql
    container_name: migra.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "migra_tests"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 6001:3306

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
